airlines=read.csv("AirlinesCluster.csv")
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
distances=dist(airlinesNorm,method="euclidean")
clusterAirlines=hclust(distances,method="ward.D")
plot(clusterAirlines)
clusterGroups = cutree(clusterAirlines, k = 5)
table(clusterGroups)
tapply(airlines$Balance, clusterGroups, mean)
tapply(airlines$QualMiles, clusterGroups, mean)
lapply(split(airlines, clusterGroups), colMeans)
k=5
set.seed(88)
KMC = kmeans(airlinesNorm, centers = k, iter.max = 1000)
table(KMC)
str(KMC)
KMCClusters = KMC$cluster
tapply(flowerVector, flowerClusters, mean)