stocks=read.csv("StocksCluster.csv")
str(stocks)
table(stocks$PositiveDec)
6324/nrow(stocks)
cor(stocks)
summary(stocks)
set.seed(144)
spl = sample.split(stocks$PositiveDec, SplitRatio = 0.7)
library(caTools)
stocksTrain = subset(stocks, spl == TRUE)
stocksTest = subset(stocks, spl == FALSE)
StocksModel=glm(PositiveDec~.,data=stocksTrain,family="binomial")
predModel1=predict(StocksModel,type="response")
table(stocksTrain$PositiveDec,predModel1>0.5)
(990+3640)/nrow(stocksTrain)
summary(predModel1)
str(predModel1)
predModel2=predict(StocksModel,newdata=stocksTest,type="response")
(417+1553)/nrow(stocksTest)
table(stocksTest$PositiveDec)
1897/nrow(stocksTest)
limitedTrain = stocksTrain
limitedTrain$PositiveDec = NULL
limitedTest = stocksTest
limitedTest$PositiveDec = NULL
library(caret)
preproc = preProcess(limitedTrain)
normTrain = predict(preproc, limitedTrain)
normTest = predict(preproc, limitedTest)
summary(normTrain)
summary(normTest)
set.seed(144)
k=3
km = kmeans(normTrain, centers = k)
table(km$cluster)
library(flexclust)
km.kcca = as.kcca(km, normTrain)
clusterTrain = predict(km.kcca)
clusterTest = predict(km.kcca, newdata=normTest)
subset(clusterTest,km$cluster==2)
table(subset(clusterTest,km$cluster==2))
str(km.kcca)
table(subset(normTest,km$cluster==2))
kmcluster2=subset(normTest,km$cluster==2)
kmcluster2=subset(stocksTest,km$cluster==2)
kmcluster2=subset(clusterTest,km$cluster==2)
table(kmcluster2)
table(clusterTest)
stocksTrain2=subset(stocksStocksModel1=glm(PositiveDec~.,data=stocksTrain1,family="binomial")
StocksModel2=glm(PositiveDec~.,data=stocksTrain2,family="binomial")
StocksModel3=glm(PositiveDec~.,data=stocksTrain3,family="binomial")
summary(StocksModel1)
summary(StocksModel2)
summary(StocksModel3)stocksTest2=subset(stocksTest,km$cluster==2)
stocksTest2=subset(stocksTest,km$cluster==2)
stocksTest1=subset(stocksTest,km$cluster==1)
stocksTest3=subset(stocksTest,km$cluster==3)
PredictTest1=predict(StocksModel1,newdata=stocksTest1,type="response")
PredictTest2=predict(StocksModel2,newdata=stocksTest2,type="response")
PredictTest3=predict(StocksModel3,newdata=stocksTest3,type="response")
table(stocksTest1$PositiveDec,PredictTest1>=0.5)
(101+498)/nrow(stocksTest1)
table(stocksTest2$PositiveDec,PredictTest2>=0.5)
(361+862)/nrow(stocksTest2)
Train,km$cluster==2)
stocksTrain1=subset(stocksTrain,km$cluster==1)
stocksTrain3=subset(stocksTrain,km$cluster==3)
summary(stocksTrain1)
summary(stocksTrain2)
summary(stocksTrain3)



