trials=read.csv("clinical_trial.csv ",stringsAsFactors=FALSE)
summary(traials)
summary(trials)
str(trials)
table(trials$abstract)
nchar(trials$abstract)
which.max(nchar(trials$abstract))
trials[664]
trials$abstract[664]
nchar(trials$abstract[664])
nrow(trials$abstract==0)
nrow(trials$abstract=0)
nrow(nchar(trials$abstract))
nrow(nchar(trials$abstract)=0)
table(nchar(trials$abstract=0))
table(nchar(trials$abstract)=0)
table(nchar(trials$abstract)==0)
which.min(nchar(trails$title))
which.min(nchar(trials$title))
trials$title[1258]
library(tm)
corpusTitle=Corpus(VectorSource(trials$title)
)
corpusAbstract=Corpus(VectorSource(trials$abstract))
corpusTitle=tm_map(corpusTitle,toLower)
corpusTitle=tm_map(corpusTitle,tolower)
corpusAbstract=tm_map(corpusAbstract,tolower)
corpusTitle = tm_map(corpusTitle, PlainTextDocument)
corpusAbstract = tm_map(corpusAbstract, PlainTextDocument)
corpusAbstract=tm_map(corpusAbstract,removePunctuation)
corpusTitle=tm_map(corpusTitle,removePunctuation)
corpusTitle=tm_map(corpusTitle,removeWords,stopwords("english"))
corpusAbstract=tm_map(corpusAbstract,removeWords,stopwords("english"))
corpusTitle=tm_map(corpusTitle,stemDocument)
corpusAbstract=tm_map(corpusAbstract,stemDocument)
dtmTitle=DocumentTermMatrix(corpusTitle)
dtmAbstract=DocumentTermMatrix(corpusAbstract)
dtmAbstract=removeSparseTerms(dtmAbstract,0.95)
dtmTitle=removeSparseTerms(dtmTitle,0.95)
dtmAbstract=as.data.frame(as.matrix(dtmAbstract))
dtmTitle=as.data.frame(as.matrix(dtmTitle))
length(stopwords("english"))
ncol(dtmTitle)
ncol(dtmAbstract)
which.max(dtmAbstract)
which.max(colSums(dtmAbstract))
colnames(dtmTitle) = paste0("T", colnames(dtmTitle))
colnames(dtmAbstract) = paste0("A", colnames(dtmAbstract))
dtm=cbind(dtmTitle,dtmAbstract)
dtm$trial=trials$trial
